export const carData = [
  {
    brandLogo: "/images/KIA_logo.png",
    brandName: "Kia",
    carImage: "/images/optima.png",
    carModel: "kia Optima 2022",
    lotNumber: "20148759950",
    currentBid: "3000",
    location: "Oman",
  },
  {
    brandLogo: "/images/KIA_logo.png",
    brandName: "Kia",
    carImage: "/images/optima.png",
    carModel: "kia Optima 2022",
    lotNumber: "20148759950",
    currentBid: "3000",
    location: "Oman",
  },
  {
    brandLogo: "/images/KIA_logo.png",
    brandName: "Kia",
    carImage: "/images/optima.png",
    carModel: "kia Optima 2022",
    lotNumber: "20148759950",
    currentBid: "3000",
    location: "Oman",
  },
  {
    brandLogo: "/images/KIA_logo.png",
    brandName: "Kia",
    carImage: "/images/optima.png",
    carModel: "kia Optima 2022",
    lotNumber: "20148759950",
    currentBid: "3000",
    location: "Oman",
  },
  {
    brandLogo: "/images/KIA_logo.png",
    brandName: "Kia",
    carImage: "/images/optima.png",
    carModel: "kia Optima 2022",
    lotNumber: "20148759950",
    currentBid: "3000",
    location: "Oman",
  },
]; // بيانات البطاقات (يمكنك تعديلها حسب الحاجة)
