export const translations: Record<Language, { [key: string]: string }> = {
  en: {
    language: "Language",
    //navegation word
    Home: "Home",
    Orders: "Orders",
    Containers: "Containers",
    Services: "Services",
    Blogs: "Blogs",
    About_us: "About us",
    Information: "Information",
    Contact_Us: "Contact Us",
    dashboard: "Dashboard",
    requests: "Requests",
    users: "Users",
    accounts: "Accounts",
    profile: "Profile",
    Settings: "Settings",
    My_Actions: "My Actions",
    //login  word
    Login: "Log in",
    login_des: "Log in to your account to continue your journey",
    Dont_have_an_account: "Dont have an account?",
    Sign_in: "Sign in",
    Forgot_password: "Forgot your password?",
    Logout: "Logout",
    //signup word
    Register: "Register",
    Signup: "Sign up",
    Signup_step1: "Choose the account type that suits you best",
    Signup_step2_private: "Sign up as private account",
    Signup_step2_company: "انشاء حساب تجاري",
    Full_name: "Full name",
    First_name: "First name",
    Last_name: "Last name",
    name: "name",
    Password: "Password",
    Old_Password: "Old_Password",
    New_Password: "New_Password",
    Email: "Email",
    company: "Company",
    company_des: "(For businesses and organizations)",
    private: "Private",
    private_des: "(For individuals)",
    Company_name: "Company name",
    //action word
    Back: "Back",
    Admin: "Admin",
    Track: "Track",
    Search: "Search",
    Enter_your_tracking_number: "Enter your tracking number",
    //hero section
    Our_Services: "Our Services",
    About_Us: "About Us",
    Add_New_Blog: "Add New Blog",
    Add_New_ٍService: "Add New Service",
    hero_title: "Simplify Your Car Import Journey!",
    hero_des:
      "Comprehensive services to import and ship cars from Canada to Oman",
    //actions
    Save: "Save",
    Change: "Change",
    Add: "Add",
    Close: "Close",
    Edit_Profile: "Edit Profile",
    //sections
    socialMidia: "Social Midia",
    Add_New_Social: "Add New Social",
    No_Social_Media_Found: "No Social Media Found",
    Choose_Icon: "Choose Icon",
    Enter_The_Link: "Enter The Link",
  },
  ar: {
    language: "اللغة",
    //navegation word
    Home: "الرئيسية",
    Orders: "الطلبات",
    Containers: "حاويات",
    Services: "الخدمات",
    Blogs: "المقالات",
    About_us: "من نحن",
    Information: "معلومات",
    Contact_Us: "تواصل معنا",
    Requests: "الطلبات",
    Users: "المستخدمون",
    Accounts: "الحسابات",
    profile: "الملف الشخصي",
    Settings: "الإعدادات",
    My_Actions: "طلباتي",
    Dashboard: "لوحة التحكم",
    //login  word
    Login: "تسجيل الدخول",
    login_des: "سجل الدخول الى حسابك لاكمال",
    Dont_have_an_account: "ليس لديك حساب؟",
    Sign_in: "تسجيل الدخول",
    Logout: "تسجيل الخروج",
    //signup word
    Register: "انشاء حساب",
    Signup: "انشاء حساب",
    Signup_step1: "اختر نوع الحساب الذي تفضل",
    Signup_step2_private: "انشاء حساب شخصي",
    Signup_step2_company: "انشاء حساب تجاري",
    Password: "كلمة المرور",
    Old_Password: "كلمة المرور القديمة",
    New_Password: "كلمة المرور الجديدة",
    Forgot_password: "هل نسيت كلمة المرور؟",
    Full_name: "الاسم الكامل",
    name: "الاسم",
    First_Name: "الاسم الاول",
    Last_Name: "الاسم الاخير",
    Email: "البريد الالكتروني",
    company: "شركة",
    company_des: "(للانشطة التجارية والمنظمات)",
    private: "شخصي",
    private_des: "(للشراء الشخصي)",
    Company_name: "اسم الشركة",
    //actions word
    Back: "رجوع",
    Admin: "المسؤول",
    Track: "مراقبة",
    Search: "بحث",
    Enter_your_tracking_number: "ادخل رقم الشحنة",
    //hero section
    Our_Services: "خدماتنا",
    About_Us: "من نحن",
    Add_New_ٍService: "اضافة خدمة جديدة",
    Add_New_Blog: "اضافة مقالة جديدة",
    hero_title: "عنوان",
    hero_des: "وصف",
    //actions
    Save: "حفظ",
    Change: "تغيير",
    Add: "اضافة",
    Close: "اغلاق",
    Edit_Profile: "تعديل الملف الشخصي",
    //sittings
    socialMidia: " التواصل الاجتماعي",
    Add_New_Social: "اضافة وسيلة جديدة",
    No_Social_Media_Found: "لا يوجد وسائل تواصل مضافة",
    Choose_Icon: "اختر ايقونة",
    Enter_The_Link: "ادخل الرابط",
  },
};

export type Language = "en" | "ar";
