export const translations: Record<Language, { [key: string]: string }> = {
  en: {
    language: "Language",
    //navegation word
    Home: "Home",
    Orders: "Orders",
    Containers: "Containers",
    Services: "Services",
    Blogs: "Blogs",
    About_us: "About us",
    Information: "Information",
    Contact_Us: "Contact Us",
    dashboard: "Dashboard",
    requests: "Requests",
    Auction: "Auction",
    Auctions: "Auctions",
    users: "Users",
    Notfications: "Notfications",
    Systim_Category: "Systim Category",
    Countries: "Countries",
    Manufacturers: "Manufacturers",
    accounts: "Accounts",
    profile: "Profile",
    Settings: "Settings",
    My_Actions: "My Actions",
    //login  word
    Login: "Log in",
    login_des: "Log in to your account to continue your journey",
    Dont_have_an_account: "Dont have an account?",
    Sign_in: "Sign in",
    Forgot_password: "Forgot your password?",
    Logout: "Logout",
    //signup word
    Register: "Register",
    Signup: "Sign up",
    Signup_step1: "Choose the account type that suits you best",
    Signup_step2_private: "Sign up as private account",
    Signup_step3_private: "Sign up as private account",
    Signup_step2_company: "Sign up as company account",
    Signup_step3_company: "Sign up as company account",
    Already_have_an_account: "Already have an account",
    Full_Name: "Full name",
    First_Name: "First name",
    Last_Name: "Last name",
    name: "name",
    Password: "Password",
    Old_Password: "Old Password",
    New_Password: "New Password",
    Email: "Email",
    company: "Company",

    Phone_Num: "Phone Number",
    Country: "Country",
    City: "City",
    ZIP_Code: "ZIP Code (optional)",
    ID_Details: "ID Details",
    id: "id",
    id_NO: "id NO",
    id_Scan: "Upload or scan your id ",
    Passport: "Passport",
    Passport_NO: "Passport NO",
    Passport_Scan: "Upload or scan your Passport",
    Another_mobile: "Alternate phone number (optional)",
    Another_Address: "Alternate address (optional)",
    Tax: "Tax Information (optional)",
    CR: " Commercial Registration",
    company_des: "(For businesses and organizations)",
    private: "Private",
    private_des: "(For individuals)",
    Main_Information: "Main Information",
    Contact_Information: "Contact Information",
    Company_name: "Company name",
    Privacy_Policy_des:
      "“By signing up, you agree to our Terms & Conditions and Privacy Policy.”",
    //action word
    Back: "Back",
    Filter: "Filter",
    Export: "Export",
    New: "New",
    Car: "Car",
    Next: "Next",
    Admin: "Admin",
    Track: "Track",
    Search: "Search",
    Yes: "Yes",
    No: "No",
    Enter_your_tracking_number: "Enter your tracking number",
    //hero section
    Our_Services: "Our Services",
    About_Us: "About Us",
    Add_New_Blog: "Add New Blog",
    Add_New_ٍService: "Add New Service",
    Edit_Blog: "Edit Blog",
    Edit_Service: "Edit Service",
    Edit: "Edit",
    hero_title: "Simplify Your Car Import Journey!",
    hero_des:
      "Comprehensive services to import and ship cars from Canada to Oman",
    What_shipping: "What are you shipping?",
    Select_address: "Select your address",
    Enter_Email: "Enter Your Email Address",
    Get_Quote: "Get Instant Quote up",
    //store
    Cars_Store: "Cars Store",
    store_title: "Car Showroom",
    store_des:
      "Shop your perfect car from our platform with ease and confidence",
    Lot_No: "Listing No.",
    Current_Bid: "Price",
    Location: "Location",
    details: "View Details",
    View_More: "View More",
    Start_Now: "Start Now",

    //global
    Showing: "Showing",
    Quick_Links: "Quick Links",
    of: "of",
    Sort_by: "Sort by",
    date: "date",
    status: "status",
    model: "model",
    View_as: "View as",
    Sales: "Salles",
    Shipping: "Shipping",
    Address: "Address",
    contact: "Contact",
    //actions
    Save: "Save",
    Change: "Change",
    Add: "Add",
    Close: "Close",
    Skip: "Skip",
    Send: "Send",

    Edit_Profile: "Edit Profile",
    Delete: "Delete",
    Accept: "Accept ",
    Reject: "Reject ",
    complete: "Mark as complete",
    Upload_Main_Image: "Upload Main Image",
    Upload_Additional_Images: "Upload Additional Images",
    //sections
    socialMidia: "Social Midia",
    Add_New_Social: "Add New Social",
    No_Social_Media_Found: "No Social Media Found",
    Choose_Icon: "Choose Icon",
    Enter_The_Link: "Enter The Link",
    Body_ar: "Body (Arabic)",
    Body_en: "Body (English)",
    desc_ar: "Description (Arabic)",
    desc_en: "Description (English)",
    title_ar: "Title (Arabic)",
    title_en: "Title (English)",
    servises_CTA_Title: "Get Started with Us Today!",
    servises_CTA_Body:
      "Whether you’re bidding on your dream car, shipping a vehicle with care, or selling a car seamlessly, we are here to provide solutions tailored to your needs.Contact us now to learn more and take the first step toward a hassle-free automotive experience!",
    //titles
    Arabic_Info: "Arabic Info",
    English_Info: "English Info",
    Upload_Images: "Upload Images",
    Terms: "Terms",
    Conditions: "Conditions",
    //toasts message
    shipping_quastion: "Has the car been shipped by us?",
    Comfirm_dellete: "Are you sure you want to delete the selected item?",
    Confirm_logout: "Are you sure you want to logout?",
    Item_deleted_successfully: "Item_deleted_successfully ✅",
    Add_Item: "The item was added successfully ✅",
    Add_Success: "ِِAdded was successfully ✅",
    Edit_Item: "The item was edited successfully ✅",
    Edit_Success: "Edited was successfully ✅",
    register_success: "✅ Account created successfully. Welcome!",
    completed_succss: "Data completed successfully",
    Error: "An error occurred ❌",
    Invalid_URL: "Invalid URL",
    Edit_Error: "An error occurred while edited ❌",
    Error_Delete: "An error occurred while deleting the item ❌",
    Error_Add_Item: "An error occurred while adding the item ❌",
    Error_Edit_Item: "An error occurred while Edited the item ❌",
    Error_Image: "Please upload an image before submitting the form ❌",
    not_allowed_upload_image: "",
    drag_and_drop_file: "",
    Error_URL: "The link is not valid ❌",
    Error_Account_type: "Please select an account type.",
    Error_Company_Name: "Please Enter the Company Name.",
    Error_Name: "Please Enter the user Name.",
    Email_required: "Please Enter the Email",
    Error_valid_email: "Please enter a valid email address.",
    Error_Email_taken: "The email has already been taken.",
    Password_required: "Password is required",
    Password_len: "Password must be at least 8 characters.",
    register_Eroor: "Signup failed please try again later.",
    Error_Email_pass: " The email or password is incorrect.",
    Logged_successfully: "Logged is successfully",
    completed_error:
      "An error occurred while completing the data, please try again later",
    //Austions word
    Select_Auction: "Select a Car for Auction",
    or: "or",
    auction_link: "Please Enter Car Auction Link",
    Car_Manufacturer: "Car Manufacturer",
    Car_Model: "Car Model",
    year: "Year of Manufacture",
    Transmission_Type: "Transmission Type",
    manual: "Manual",
    auto: "Auto",
    Tiptronic: "Tiptronic",
    Drive_System: "Drive System",
    FWD: "FWD",
    RWD: "RWD",
    d4WD: "4WD",
    Fuel_Type: "Fuel Type",
    Petrol: "Petrol",
    Disel: "Disel",
    CNG: "CNG (GAZ)",
    Flex_Fuel: "Flex Fuel",
    Hybrid: "Hybrid",
    Electric: "Electric",
    Number_of_Cylinders: "Number of Cylinders",
    Budget_Range: "Budget Range",
    From: "From",
    To: "To",
    Shipping_Option: "Shipping Option",
    container: "container",
    group: "group",
    Shipping_Country: "Shipping Country",
    Exterior_Color: "Exterior Color",
    Interior_Color: "Interior Color",
    white: "white",
    black: "black",
    silver: "silver",
    gray: "gray",
    red: "red",
    blue: "blue",
    green: "green",
    yellow: "yellow",
    orange: "orange",
    brown: "brown",
    beige: "beige",
    gold: "gold",
    maroon: "maroon",
    navy: "navy",
    purple: "purple",
    tan: "tan",
    cream: "cream",
    dark_blue: "dark_blue",
    burgundy: "burgundy",
    ivory: "ivory",
    loading: "loading ...",
    no_options: "no options ",
    Send_Car_Order: "Send Car Order ",
    Edit_Auction: "The auction was successfully updated.",
    Add_Auction: "The auction was successfully Added.",
    choes_Manufacturer_first: "choes Manufacturer first",
    choes_category_first: "choes category first",
    //sales words
    Edit_sales: "The car sale was successfully updated.",
    Add_sales: "The car sale was successfully Added.",
    Car_Sales: "Car Sales",
    Car_Information: "Car Information",
    Category: "Category",
    Mileage: "Mileage",
    Specifications: "Specifications",
    Price: "Price",
    Car_Status: "Car Status",
    Used: "Used",
    Modified: "Modified",
    Accidented: "Accidented",
    Disabled: "Disabled",
    Shipping_Location: "Shipping & Location",
    Shipping_from: "Shipping from",
    Shipping_Status: "Shipping Status",
    In_Stock: "In Stock",
    In_Transit: "In Transit",
    Arrived: "Arrived",
    Location_of_Car: "Location of Car",
    If_shipped: "If shipped",
    if_not_shipped: "If not shipped",
    On_the_way: "On the way",
    In_transit: "In transit",
    Additional_Features: "Additional Features",
    Carfax: "Carfax",
    Available: "Available",
    Not_available: "Not available",
    Sohar: "Sohar",
    Duqm: "Duqm",
    Car_Images: "Car Images",
    Upload_multiple_images: "Upload multiple images",
    Cancel: "Cancel",
    Send_Offer: "Send Offer",
  },
  ar: {
    /////////////////////////////
    language: "اللغة",
    //navegation word
    Home: "الرئيسية",
    Orders: "الطلبات",
    Containers: "حاويات",
    Services: "الخدمات",
    Blogs: "المقالات",
    About_us: "من نحن",
    Information: "معلومات",
    Contact_Us: "تواصل معنا",
    Requests: "الطلبات",
    Auction: "المزاد",
    Auctions: "المزادات",
    Users: "المستخدمون",
    Notfications: "الاشعارات",
    Systim_Category: "فئات النظام",
    Countries: "البلدان",
    Manufacturers: "انواع السيارات",
    Accounts: "الحسابات",
    profile: "الملف الشخصي",
    Settings: "الإعدادات",
    My_Actions: "طلباتي",
    Dashboard: "لوحة التحكم",
    //login  word
    Login: "تسجيل الدخول",
    login_des: "سجل الدخول الى حسابك لاكمال",
    Dont_have_an_account: "ليس لديك حساب؟",
    Sign_in: "تسجيل الدخول",
    Logout: "تسجيل الخروج",
    //signup word
    Register: "انشاء حساب",
    Signup: "انشاء حساب",
    Already_have_an_account: "لدي حساب بالفعل",
    Signup_step1: "اختر نوع الحساب الذي تفضل",
    Signup_step2_private: "انشاء حساب شخصي",
    Signup_step3_private: "انشاء حساب شخصي",
    Signup_step2_company: "انشاء حساب تجاري",
    Signup_step3_company: "انشاء حساب تجاري",
    Password: "كلمة المرور",
    Old_Password: "كلمة المرور القديمة",
    New_Password: "كلمة المرور الجديدة",
    Forgot_password: "هل نسيت كلمة المرور؟",
    Full_Name: "الاسم الكامل",
    name: "الاسم",
    First_Name: "الاسم الاول",
    Last_Name: "الاسم الاخير",
    Email: "البريد الالكتروني",
    company: "شركة",
    Company_name: "اسم الشركة",
    Phone_Num: "رقم الجوال",
    Country: "البلد",
    City: "المدينة",
    ID_Details: "تفاصيل الهوية",
    ZIP_Code: "الرمز البريدي (اختياري)",
    Another_Address: "عنوان آخر (اختياري)",
    Another_mobile: "رقم جوال آخر (اختياري)",
    id: "الهوية",
    id_NO: "رقم الهوية",
    id_Scan: "حمّل أو امسح هويتك ضوئيًا",
    Passport: "جواز السفر",
    Passport_NO: " رقم جواز السفر",
    Passport_Scan: "حمّل أو امسح جواز سفرك ضوئيًا",
    CR: "السجل التجاري",
    Tax: "المعلومات  الضريبية (اختياري)",
    company_des: "(للانشطة التجارية والمنظمات)",
    private: "شخصي",
    private_des: "(للشراء الشخصي)",
    Main_Information: "المعلومات الاساسية",
    Contact_Information: "معلومات التواصل",
    Privacy_Policy_des:
      "“بانشائك للحساب انت توافق على شروط الاستخدام وسياسة الخصوصية”",
    //global
    Showing: "عرض العناصر",
    Quick_Links: "روابط سريعة",
    of: "من",
    Sort_by: "ترتيب حسب",
    date: "التاريخ",
    status: "الحالة",
    model: "الموديل",
    View_as: "عرض ك",
    Sales: "طلبات البيع",
    Shipping: "طلبات الشحن",
    //actions word
    Back: "رجوع",
    Filter: "تصفية",
    Export: "تصدير",
    New: "جديد",
    Car: "سيارة",
    Next: "التالي",
    Admin: "المسؤول",
    Track: "مراقبة",
    Search: "بحث",
    Yes: "نعم",
    No: "لا",
    Enter_your_tracking_number: "ادخل رقم الشحنة",
    //hero section
    Our_Services: "خدماتنا",
    About_Us: "من نحن",
    Add_New_ٍService: "اضافة خدمة جديدة",
    Add_New_Blog: "اضافة مقالة جديدة",
    Edit_Blog: "تعديل المقالة",
    Edit: "تعديل ",
    Delete: "حذف ",
    Accept: "قبول ",
    Reject: "رفض ",
    complete: "تعيين ك منجز ",
    hero_title: "بسّط رحلة استيراد سيارتك!",
    hero_des: "خدمات شاملة لاستيراد وشحن السيارات من كندا إلى سلطنة عُمان",
    What_shipping: "ماذا تريد ان تشحن؟",
    Select_address: "اختر عنوانك",
    Enter_Email: "أدخل عنوان بريدك الإلكتروني",
    Get_Quote: "احصل على عرض سعر فوري",
    Address: "العنوان",
    contact: "التواصل",
    //store
    Cars_Store: "معرض السيارات",
    store_title: "معرض السيارات",
    store_des: "تسوّق سيارتك المثالية من منصتنا بكل سهولة وثقة",

    Lot_No: "رقم العرض",
    Current_Bid: "السعر",
    Location: "الموقع",
    details: "عرض التفاصيل",
    View_More: "عرض المزيد",
    Start_Now: "ابدأ الان",

    //actions
    Save: "حفظ",
    Change: "تغيير",
    Add: "اضافة",
    Close: "اغلاق",
    Skip: "تخطي",
    Send: "ارسال",
    Edit_Profile: "تعديل الملف الشخصي",
    Body_ar: "النص (عربي)",
    Body_en: "النص (انجليزي)",
    desc_ar: "الوصف (عربي)",
    desc_en: "الوصف (انجليزي)",
    title_ar: "العنوان (عربي)",
    title_en: "العنوان (انجليزي)",
    servises_CTA_Title: "ابدأ تجربتك معنا اليوم !",
    servises_CTA_Body: "ابدأ معنا اليوم !",
    Upload_Main_Image: "اختر الصورة الرئيسية",
    Upload_Additional_Images: "ارفع المزيد من الصور(اختياري)...",
    //titles
    Arabic_Info: "المقال بالعربي",
    English_Info: "المقال الانجليزي",
    Upload_Images: "تحميل الصور",
    Terms: "السياسات",
    Conditions: "الشروط",
    //sittings
    socialMidia: " التواصل الاجتماعي",
    Add_New_Social: "اضافة وسيلة جديدة",
    No_Social_Media_Found: "لا يوجد وسائل تواصل مضافة",
    Choose_Icon: "اختر ايقونة",
    Enter_The_Link: "ادخل الرابط",
    //toasts message
    shipping_quastion: "هل تم شحن السيارة بواسطتنا؟ ",
    Comfirm_dellete: "هل انت متاكد من حذف العنصر؟",
    Confirm_logout: "هل انت متاكد من تسجيل الخروج؟",
    Item_deleted_successfully: "تم حذف العنصر بنجاح ✅",
    Add_Item: "تم اضافة العنصر بنجاح ✅",
    Add_Success: "تمت الاضافة بنجاح ✅",
    Edit_Item: "تم تعديل العنصر بنجاح ✅",
    Edit_Success: "تم التعديل بنجاح ✅",
    register_success: "✅ تم إنشاء الحساب بنجاح. مرحبًا بك!",
    completed_succss: "تم اكمال البيانات بنجاح",
    Edit_Error: "حدث خطا اثناء التعديل ❌",
    Invalid_URL: " الرابط غير صالح",
    Error: "حدث خطا ما ❌",
    Error_Delete: "حدث خطا اثناء حذف العنصر ❌",
    Error_Add_Item: " حدث خطا اثناء اضافة العنصر ❌",
    Error_Edit_Item: " حدث خطا اثناء تعديل العنصر ❌",
    Error_Image: "الرجاء رفع صورة قبل إرسال النموذج  ❌",
    not_allowed_upload_file: "لا يمكنك رفع اكثر من ملف",
    drag_and_drop_file: "اسحب وأفلت الصور هنا أو انقر لاختيار الملفات",
    Error_URL: "الرابط غير صالح ❌",
    Error_Account_type: "الرجاء اختيار نوع الحساب",
    Error_Name: "الرجاء ادخال اسم مستخدم",
    Error_Company_Name: " الرجاء ادخال اسم الشركة",
    Email_required: "الرجاء ادخال البريد الاكتروني",
    Error_valid_email: "الرجاء ادخال بريد الكتروني صالح",
    Error_Email_taken:
      "البريد الإلكتروني مستخدم بالفعل، يرجى استخدام بريد آخر.",
    Password_required: "الرجاء ادخال كلمة مرور",
    Password_len: "يرجى ادخال كلمة مرور اكبر من 8 حروف او ارقام او رموز ",
    register_Eroor: "حدث خطأ في التسجيل، يرجى المحاولة مرة أخرى.",
    Error_Email_pass: "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
    Logged_successfully: "تم تسجيل الدخول بنجاح.",
    completed_error: "حدث خطأ أثناء إكمال البيانات الرجاء المحاولة لاحقًا",
    //Auctions word
    Select_Auction: "اختر سيارة للمزاد",
    or: "او",
    auction_link: "ادخل رابط مزاد السيارة من فضلك",
    Car_Manufacturer: "الشركة الصانعة",
    Car_Model: "طراز السيارة",
    year: "سنة الصنع",
    Transmission_Type: "نوع ناقل الحركة",
    manual: "عادي",
    auto: "اوتوماتيك",
    Tiptronic: "تيبترونك (مشترك)",
    Drive_System: "نظام القيادة",
    FWD: "شد امامي",
    RWD: "دفع خلفي",
    d4WD: "دفع رباعي",
    Fuel_Type: "نوع الوقود",
    Petrol: "بنزين",
    Disel: "مازوت",
    CNG: "CNG (غاز)",
    Flex_Fuel: "وقود مرن",
    Hybrid: "هجينة",
    Electric: "كهربائية",
    Number_of_Cylinders: "عدد الاسطوانات",
    Budget_Range: "مجال السعر",
    From: "من",
    To: "الى",
    Shipping_Option: "خيار الشحن",
    container: "حاوية منفصلة",
    group: "مجموعة",
    Shipping_Country: "بلد الشحن",
    Exterior_Color: "اللون الخارجي",
    Interior_Color: "اللون الداخلي",
    white: "أبيض",
    black: "أسود",
    silver: "فضي",
    gray: "رمادي",
    red: "أحمر",
    blue: "أزرق",
    green: "أخضر",
    yellow: "أصفر",
    orange: "برتقالي",
    brown: "بني",
    beige: "بيج",
    gold: "ذهبي",
    maroon: "خمري",
    navy: "كحلي",
    purple: "أرجواني",
    tan: "كستنائي فاتح",
    cream: "كريمي",
    dark_blue: "أزرق داكن",
    burgundy: "عنابي",
    ivory: "عاجي",
    loading: "جاري التحميل ...",
    no_options: "لا توجد خيارات متاحة",
    Send_Car_Order: "ارسال طلب المزاد",
    Edit_Auction: "تم تعديل المزاد بنجاح",
    Add_Auction: "تمت اضافة المزاد بنجاح",
    choes_Manufacturer_first: "اختر الشركة الصانعة اولا",
    //sales words
    Edit_sales: "تم تعديل عرض البيع بنجاح",
    Add_sales: "تم اضافة عرض البيع بنجاح",
    Car_Sales: "بيع السيارة",
    Car_Information: "معلومات السيارة",
    Category: "الفئة",
    Mileage: "العداد",
    Specifications: "Specifications",
    Price: "السعر",
    Car_Status: "حالة السيارة",
    Used: "مستعملة",
    Modified: "معدلة",
    Accidented: "حادث",
    Disabled: "معطلة",
    Shipping_Location: "الشحن و الموقع",
    Shipping_from: "الشحن من",
    Shipping_Status: "حالة الشحن",
    In_Stock: "في المخزن",
    In_Transit: "قيد الشحن",
    Arrived: "وصلت",
    Location_of_Car: "موقع السيارة",
    If_shipped: "اذا تم الشحن",
    if_not_shipped: "اذا لم يتم الشحن",
    On_the_way: "في الطريق",
    In_transit: "قيد الشحن",
    Additional_Features: "ميزات إضافية",
    Carfax: "تقرير Carfax",
    Available: "متاح",
    Not_available: "غير متاح",
    Sohar: "صحار",
    Duqm: "الدقم",
    Car_Images: "صور السيارة",
    Upload_multiple_images: "ارفع صور متعددة",
    Cancel: "الغاء",
    Send_Offer: "ارسال العرض",
  },
};

export type Language = "en" | "ar";
