export const translations: Record<Language, { [key: string]: string }> = {
  en: {
    Home: "Home",
    Services: "Services",
    About_us: "About us",
    Information: "Information",
    Contact_Us: "Contact Us",
    requests: "Requests",
    users: "Users",
    accounts: "Accounts",
    profile: "Profile",
    settings: "Settings",
    dashboard: "Dashboard",
    Login: "Log in",
    login_des: "Log in to your account to continue your journey",
    Dont_have_an_account: "Dont have an account?",
    Sign_in: "Sign in",
    Register: "Register",
    Signup: "Sign up",
    Signup_step1: "Choose the account type that suits you best",
    Signup_step2_private: "Sign up as private account",
    Signup_step2_company: "انشاء حساب تجاري",
    Password: "Password",
    Forgot_password: "Forgot your password?",
    Email: "Email",
    Admin: "Admin",
    Track: "Track",
    Enter_your_tracking_number: "Enter your tracking number",
  },
  ar: {
    Home: "الرئيسية",
    Services: "الخدمات",
    About_us: "من نحن",
    Information: "معلومات",
    Contact_Us: "تواصل معنا",
    Requests: "الطلبات",
    Users: "المستخدمون",
    Accounts: "الحسابات",
    profile: "الملف الشخصي",
    Settings: "الإعدادات",
    Dashboard: "لوحة التحكم",
    Login: "تسجيل الدخول",
    login_des: "سجل الدخول الى حسابك لاكمال",
    Dont_have_an_account: "ليس لديك حساب؟",
    Sign_in: "تسجيل الدخول",
    Register: "انشاء حساب",
    Signup: "انشاء حساب",
    Signup_step1: "اختر نوع الحساب الذي تفضل",
    Signup_step2_private: "انشاء حساب شخصي",
    Signup_step2_company: "انشاء حساب تجاري",
    Password: "كلمة المرور",
    Forgot_password: "هل نسيت كلمة المرور؟",
    Email: "البريد الالكتروني",
    Admin: "المسؤول",
    Track: "مراقبة",
    Enter_your_tracking_number: "ادخل رقم الشحنة",
  },
};

export type Language = "en" | "ar";
